### ISSUE TITLE
cache logfile lines are messed up

### ISSUE THREAD

**Issue by bobzhang** [jrosdahl/ccache#48] opened 2015-04-15 21:33 UTC
with the master branch, when I turned logfile on, the logs are messed up in a single line, so if I have parallel build building object a's log will mix with building object b's log.
even a single line is not integral,
is this expected behavior? thanks

**Comment by bobzhang** [comment] 2015-04-15 21:35
I did not observe such behavior on version 3.1.11, only on master branch

**Comment by jrosdahl** [comment] 2015-04-16 20:21
It's not expected behavior. However, I can't reproduce the described behavior. Which platform are you using?

**Comment by bobzhang** [comment] 2015-04-29 03:09
It's on  solaris platform

**Comment by jrosdahl** [comment] 2015-05-01 08:45
"Solaris" is not very specific. Which version? Which architecture? Which compiler are you using? Etc, etc.  When reporting bugs, please spend some time to think about what the bug report receiver needs to know. It's not fun having to spend time guessing when the time instead could be used to try to find the bug.

That said, I can't reproduce the problem on Solaris 10 Sparc with GCC 4.9.2. You will have to help me find the bug.

**Comment by jrosdahl** [comment] 2015-08-07 14:52
Hi again!

Would it be possible for you to supply some more details on the problem? That would be very helpful. Thanks!

**Comment by bobzhang** [comment] 2015-08-08 03:42
I will try master branch to see if I can reproduce it next week

**Comment by jrosdahl** [comment] 2015-10-25 13:07
Hi Bob,

Any news on this?

Thanks!

**Comment by jrosdahl** [comment] 2015-12-19 14:45
Not reproducible and no answer from bug reporter, so closing.

**Closed by jrosdahl** 2015-12-19 14:45 UTC
